/*
 * This file is generated by jOOQ.
*/
package com.phpbae.jooq.model;


import com.phpbae.jooq.model.tables.Customer;
import com.phpbae.jooq.model.tables.Product;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.customer</code>.
     */
    public static final Customer CUSTOMER = com.phpbae.jooq.model.tables.Customer.CUSTOMER;

    /**
     * The table <code>test.product</code>.
     */
    public static final Product PRODUCT = com.phpbae.jooq.model.tables.Product.PRODUCT;
}
